"""
Better-Auth API endpoints for the RAG Chatbot backend.
This module provides authentication endpoints that integrate with the frontend Better-Auth client.
"""
from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import JSONResponse
from typing import Optional
import betterproto
from datetime import datetime
from ..utils.logger import logger
from ..utils.config import settings
from ..services.auth_service import get_auth_service, UserProfileCreate, UserProfileUpdate

router = APIRouter(prefix="/api/auth", tags=["auth"])

@router.post("/signup")
async def signup(
    request: Request,
    email: str,
    password: str,
    name: str,
    hardware_type: Optional[str] = None,
    hardware_details: Optional[dict] = None
):
    """
    Handle user signup requests from Better-Auth frontend.
    Creates a user profile with hardware information.
    """
    try:
        # Get the auth service instance
        auth_service = get_auth_service()

        # Create user profile with hardware information
        profile_data = UserProfileCreate(
            user_id="temp_user_id",  # This would be generated by Better-Auth
            email=email,
            name=name,
            hardware_type=hardware_type,
            hardware_details=hardware_details
        )

        # Create the user profile in the database
        user_profile = await auth_service.create_user_profile(profile_data)

        # Return success response
        return JSONResponse(
            status_code=200,
            content={
                "success": True,
                "message": "User created successfully",
                "user": {
                    "id": user_profile.user_id,
                    "email": user_profile.email,
                    "name": user_profile.name
                }
            }
        )
    except Exception as e:
        logger.error(f"Signup error: {str(e)}")
        raise HTTPException(status_code=400, detail=f"Signup failed: {str(e)}")


@router.post("/login")
async def login(
    request: Request,
    email: str,
    password: str
):
    """
    Handle user login requests from Better-Auth frontend.
    Validates credentials and returns user information.
    """
    try:
        # In a real implementation, this would validate credentials
        # For now, we'll simulate a successful login
        return JSONResponse(
            status_code=200,
            content={
                "success": True,
                "message": "Login successful",
                "user": {
                    "id": "temp_user_id",
                    "email": email,
                    "name": "Temp User Name"  # Would come from database
                }
            }
        )
    except Exception as e:
        logger.error(f"Login error: {str(e)}")
        raise HTTPException(status_code=400, detail=f"Login failed: {str(e)}")


@router.get("/user/{user_id}")
async def get_user_profile(user_id: str):
    """
    Get user profile information by user ID.
    """
    try:
        auth_service = get_auth_service()
        user_profile = await auth_service.get_user_profile(user_id)

        if not user_profile:
            raise HTTPException(status_code=404, detail="User not found")

        return JSONResponse(
            status_code=200,
            content={
                "user": {
                    "id": user_profile.user_id,
                    "email": user_profile.email,
                    "name": user_profile.name,
                    "hardware_type": user_profile.hardware_type,
                    "hardware_details": user_profile.hardware_details.dict() if user_profile.hardware_details else None,
                    "created_at": user_profile.created_at.isoformat(),
                    "updated_at": user_profile.updated_at.isoformat()
                }
            }
        )
    except Exception as e:
        logger.error(f"Get user profile error: {str(e)}")
        raise HTTPException(status_code=400, detail=f"Failed to get user profile: {str(e)}")


@router.put("/user/{user_id}")
async def update_user_profile(
    user_id: str,
    name: Optional[str] = None,
    hardware_type: Optional[str] = None,
    hardware_details: Optional[dict] = None
):
    """
    Update user profile information.
    """
    try:
        auth_service = get_auth_service()

        profile_update = UserProfileUpdate(
            name=name,
            hardware_type=hardware_type,
            hardware_details=hardware_details
        )

        updated_profile = await auth_service.update_user_profile(user_id, profile_update)

        if not updated_profile:
            raise HTTPException(status_code=404, detail="User not found")

        return JSONResponse(
            status_code=200,
            content={
                "success": True,
                "message": "Profile updated successfully",
                "user": {
                    "id": updated_profile.user_id,
                    "email": updated_profile.email,
                    "name": updated_profile.name,
                    "hardware_type": updated_profile.hardware_type,
                    "hardware_details": updated_profile.hardware_details.dict() if updated_profile.hardware_details else None,
                    "updated_at": updated_profile.updated_at.isoformat()
                }
            }
        )
    except Exception as e:
        logger.error(f"Update user profile error: {str(e)}")
        raise HTTPException(status_code=400, detail=f"Failed to update user profile: {str(e)}")


@router.post("/logout")
async def logout(request: Request):
    """
    Handle user logout requests.
    """
    try:
        return JSONResponse(
            status_code=200,
            content={
                "success": True,
                "message": "Logout successful"
            }
        )
    except Exception as e:
        logger.error(f"Logout error: {str(e)}")
        raise HTTPException(status_code=400, detail=f"Logout failed: {str(e)}")