import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { createAuthClient, getCurrentSession } from 'better-auth/react';

// Define types for user and hardware profile
interface HardwareProfile {
  id: string;
  userId: string;
  hardwareType: 'gpu_workstation' | 'edge_device' | 'cloud_mac' | null;
  gpuModel?: string;
  cpuModel?: string;
  ramSize?: number;
  osType?: string;
  additionalNotes?: string;
  createdAt: string;
  updatedAt: string;
}

interface UserProfile {
  id: string;
  email: string;
  name: string;
  hardwareProfile: HardwareProfile | null;
  createdAt: string;
  updatedAt: string;
}

interface AuthContextType {
  user: UserProfile | null;
  isLoading: boolean;
  signIn: (email: string, password: string) => Promise<void>;
  signUp: (email: string, password: string, name: string, hardwareProfile: Omit<HardwareProfile, 'id' | 'userId' | 'createdAt' | 'updatedAt'>) => Promise<void>;
  signOut: () => Promise<void>;
  updateHardwareProfile: (hardwareData: Omit<HardwareProfile, 'id' | 'userId' | 'createdAt' | 'updatedAt'>) => Promise<void>;
}

// Initialize Better-Auth client
const authClient = createAuthClient({
  baseURL: process.env.NODE_ENV === 'production'
    ? 'https://humanoidbackend.vercel.app'  // Update with your actual backend URL
    : 'http://localhost:8000',
  fetch: globalThis.fetch,
});

const AuthContext = createContext<AuthContextType | undefined>(undefined);

interface AuthProviderProps {
  children: ReactNode;
}

export const AuthProvider: React.FC<AuthProviderProps> = ({ children }) => {
  const [user, setUser] = useState<UserProfile | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  // Check session on component mount
  useEffect(() => {
    const checkSession = async () => {
      try {
        const session = await getCurrentSession(authClient);
        if (session?.user) {
          // Fetch user profile including hardware profile
          const userProfile = await fetchUserProfile(session.user.id);
          setUser(userProfile);
        }
      } catch (error) {
        console.error('Error checking session:', error);
      } finally {
        setIsLoading(false);
      }
    };

    checkSession();
  }, []);

  const fetchUserProfile = async (userId: string): Promise<UserProfile> => {
    // This would be an API call to your backend to get user profile
    // For now, returning a mock profile
    return {
      id: userId,
      email: 'user@example.com', // This would come from the session
      name: 'John Doe', // This would come from the session
      hardwareProfile: null, // This would be fetched from your database
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
  };

  const signIn = async (email: string, password: string) => {
    setIsLoading(true);
    try {
      // Sign in using Better-Auth
      const response = await authClient.signIn.email({
        email,
        password,
        callbackURL: '/', // Redirect after sign in
      });

      if (response?.user) {
        const userProfile = await fetchUserProfile(response.user.id);
        setUser(userProfile);
      }
    } catch (error) {
      console.error('Sign in error:', error);
      throw error;
    } finally {
      setIsLoading(false);
    }
  };

  const signUp = async (
    email: string,
    password: string,
    name: string,
    hardwareProfile: Omit<HardwareProfile, 'id' | 'userId' | 'createdAt' | 'updatedAt'>
  ) => {
    setIsLoading(true);
    try {
      // Sign up using Better-Auth
      const response = await authClient.signUp.email({
        email,
        password,
        name,
        callbackURL: '/', // Redirect after sign up
      });

      if (response?.user) {
        // Create user profile with hardware information
        const userProfile = await createUserProfile(response.user.id, name, email, hardwareProfile);
        setUser(userProfile);
      }
    } catch (error) {
      console.error('Sign up error:', error);
      throw error;
    } finally {
      setIsLoading(false);
    }
  };

  const createUserProfile = async (
    userId: string,
    name: string,
    email: string,
    hardwareData: Omit<HardwareProfile, 'id' | 'userId' | 'createdAt' | 'updatedAt'>
  ): Promise<UserProfile> => {
    // This would be an API call to your backend to create user profile
    // For now, returning a mock profile
    return {
      id: userId,
      email,
      name,
      hardwareProfile: {
        ...hardwareData,
        id: 'temp-id', // This would be generated by your backend
        userId,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
  };

  const signOut = async () => {
    setIsLoading(true);
    try {
      await authClient.signOut();
      setUser(null);
    } catch (error) {
      console.error('Sign out error:', error);
      throw error;
    } finally {
      setIsLoading(false);
    }
  };

  const updateHardwareProfile = async (
    hardwareData: Omit<HardwareProfile, 'id' | 'userId' | 'createdAt' | 'updatedAt'>
  ) => {
    if (!user) {
      throw new Error('User not authenticated');
    }

    setIsLoading(true);
    try {
      // Update hardware profile via API call
      const updatedProfile = await updateHardwareProfileAPI(user.id, hardwareData);
      setUser({
        ...user,
        hardwareProfile: updatedProfile,
      });
    } catch (error) {
      console.error('Update hardware profile error:', error);
      throw error;
    } finally {
      setIsLoading(false);
    }
  };

  const updateHardwareProfileAPI = async (
    userId: string,
    hardwareData: Omit<HardwareProfile, 'id' | 'userId' | 'createdAt' | 'updatedAt'>
  ): Promise<HardwareProfile> => {
    // This would be an API call to your backend to update hardware profile
    // For now, returning a mock profile
    return {
      ...hardwareData,
      id: 'temp-id',
      userId,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
  };

  return (
    <AuthContext.Provider
      value={{
        user,
        isLoading,
        signIn,
        signUp,
        signOut,
        updateHardwareProfile,
      }}
    >
      {children}
    </AuthContext.Provider>
  );
};

export const useAuth = (): AuthContextType => {
  const context = useContext(AuthContext);
  if (context === undefined) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
};